PREFIX ctc: <http://www.semanticweb.org/nicol/ontologies/2020/4/CTConcepts/>
PREFIX scratch: <http://www.semanticweb.org/nicol/ontologies/scratch/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
# SELECT ?evaluation ?project ?flow_control
# ?has_sequence ?has_repeat ?has_repeat_until
# ?flow_control_score
# ?object ?has_if ?has_else ?has_logical_op ?logic_score
CONSTRUCT {
	?flow_control ctc:ConceptScore ?flow_control_score
}
WHERE {
	?evaluation rdf:type ctc:CTEvaluation .
	?evaluation ctc:evaluates ?flow_control .
	?flow_control rdf:type ctc:FlowControl .

	?evaluation ctc:uses ?project .
	?project rdf:type scratch:Project .

	# Rule 1
	OPTIONAL{ ?block1 scratch:Connects ?block2 . }
	# Rule 2
	OPTIONAL{
    { ?repeat rdf:type scratch:ForeverBlock } UNION
    { ?repeat rdf:type <http://www.semanticweb.org/nicol/ontologies/scratch/Repeat()Block> }
  }
	# Rule 3
	OPTIONAL{
    ?repeat_until rdf:type <http://www.semanticweb.org/nicol/ontologies/scratch/RepeatUntil()Block>
  }

	BIND(BOUND(?block2) AS ?has_sequence)
	BIND(BOUND(?repeat) AS ?has_repeat)
	BIND(BOUND(?repeat_until) AS ?has_repeat_until)

	BIND(
		if(
			?has_repeat_until,
			3,
			if(
				?has_repeat,
				2,
				if(
					?has_sequence,
					1,
					0
				)
			)
		)
	AS ?flow_control_score)
}
