PREFIX ctc: <http://www.semanticweb.org/nicol/ontologies/2020/4/CTConcepts/>
PREFIX scratch: <http://www.semanticweb.org/nicol/ontologies/scratch/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT  ?evaluation ?project ?if_block ?logic_score
WHERE {
	?evaluation rdf:type ctc:CTEvaluation .
	?evaluation ctc:evaluates ?logical_thinking .
	?logical_thinking rdf:type ctc:LogicalThinking .

	?evaluation ctc:uses ?project .
	?project rdf:type scratch:Project .

	# Case 1
	BIND (
		EXISTS {
			?project scratch:owns ?if_block .
			?if_block rdf:type <http://www.semanticweb.org/nicol/ontologies/scratch/If()ThenBlock> .
		}
	AS ?has_if) .

	# Case 2
	BIND (
		EXISTS {
			?project scratch:owns ?if_else_block .
			?if_else_block rdf:type <http://www.semanticweb.org/nicol/ontologies/scratch/If()ThenElseBlock> .
		}
	AS ?has_if_else) .

	BIND(
		if(
			?has_if_else,
		    	2,
			if(
				?has_if,
				1,
				0
			)
		)
	AS ?logic_score)



}