PREFIX ctc: <http://www.semanticweb.org/nicol/ontologies/2020/4/CTConcepts/>
PREFIX scratch: <http://www.semanticweb.org/nicol/ontologies/scratch/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
# SELECT ?evaluation ?project ?object ?has_if ?has_else ?has_logical_op ?logic_score
CONSTRUCT {
	?logical_thinking ctc:ConceptScore ?logic_score
}
WHERE {
	?evaluation rdf:type ctc:CTEvaluation .
	?evaluation ctc:evaluates ?logical_thinking .
	?logical_thinking rdf:type ctc:LogicalThinking .

	?evaluation ctc:uses ?project .
	?project rdf:type scratch:Project .

	# Rule 1
	OPTIONAL{ ?if_block rdf:type <http://www.semanticweb.org/nicol/ontologies/scratch/If()ThenBlock> }
	# Rule 2
	OPTIONAL{ ?if_else_block rdf:type <http://www.semanticweb.org/nicol/ontologies/scratch/If()ThenElseBlock> }
	# Rule 3
	OPTIONAL {
		{ ?logical_operator_block rdf:type <http://www.semanticweb.org/nicol/ontologies/scratch/()And()Block> } UNION
		{ ?logical_operator_block rdf:type <http://www.semanticweb.org/nicol/ontologies/scratch/()Or()Block> } UNION
		{ ?logical_operator_block rdf:type <http://www.semanticweb.org/nicol/ontologies/scratch/Not()Block> }
	}

	BIND(BOUND(?if_block) AS ?has_if)
	BIND(BOUND(?if_else) AS ?has_else)
	BIND(BOUND(?logical_operator_block) AS ?has_logical_op)

	BIND(
		if(
			?has_logical_op,
			3,
			if(
				?has_if_else,
				2,
				if(
					?has_if,
					1,
					0
				)
			)
		)
	AS ?logic_score)
}
