PREFIX ctc: <http://www.semanticweb.org/nicol/ontologies/2020/4/CTConcepts/>
PREFIX scratch: <http://www.semanticweb.org/nicol/ontologies/scratch/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT  ?evaluation (SUM(?score) AS ?total_score)
WHERE {
	?concept rdf:type ctc:CTConcept .
	?concept ctc:ConceptScore ?score .
	?evaluation ctc:evaluates ?concept
}
GROUP BY ?evaluation